// Date: 28/07/2015 17:14:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package eryah.usefulthings.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMotoBoat extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Rembarde_Avant;
    ModelRenderer Rembarde_Arrière;
    ModelRenderer Rembarde_Droite;
    ModelRenderer Rembarde_Gauche;
    ModelRenderer Moteur_Center;
    ModelRenderer Moteur_Droite;
    ModelRenderer Moteur_Gauche;
  
  public ModelMotoBoat()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 16, 4, 24);
      Base.setRotationPoint(-8F, 20F, -12F);
      Base.setTextureSize(128, 64);
      setRotation(Base, 0F, 0F, 0F);
      Rembarde_Avant = new ModelRenderer(this, 86, 0);
      Rembarde_Avant.addBox(0F, 0F, 0F, 16, 6, 2);
      Rembarde_Avant.setRotationPoint(-8F, 14F, -12F);
      Rembarde_Avant.setTextureSize(128, 64);
      setRotation(Rembarde_Avant, 0F, 0F, 0F);
      Rembarde_Arrière = new ModelRenderer(this, 86, 0);
      Rembarde_Arrière.addBox(0F, 0F, 0F, 16, 6, 2);
      Rembarde_Arrière.setRotationPoint(-8F, 14F, 10F);
      Rembarde_Arrière.setTextureSize(128, 64);
      setRotation(Rembarde_Arrière, 0F, 0F, 0F);
      Rembarde_Droite = new ModelRenderer(this, 75, 11);
      Rembarde_Droite.addBox(0F, 0F, 0F, 2, 6, 24);
      Rembarde_Droite.setRotationPoint(-10F, 14F, -12F);
      Rembarde_Droite.setTextureSize(128, 64);
      setRotation(Rembarde_Droite, 0F, 0F, 0F);
      Rembarde_Gauche = new ModelRenderer(this, 75, 11);
      Rembarde_Gauche.addBox(0F, 0F, 0F, 2, 6, 24);
      Rembarde_Gauche.setRotationPoint(8F, 14F, -12F);
      Rembarde_Gauche.setTextureSize(128, 64);
      setRotation(Rembarde_Gauche, 0F, 0F, 0F);
      Moteur_Center = new ModelRenderer(this, 16, 32);
      Moteur_Center.addBox(0F, 0F, 0F, 2, 3, 2);
      Moteur_Center.setRotationPoint(-1F, 19F, 12F);
      Moteur_Center.setTextureSize(128, 64);
      setRotation(Moteur_Center, 0F, 0F, 0F);
      Moteur_Droite = new ModelRenderer(this, 0, 32);
      Moteur_Droite.addBox(0F, 0F, 0F, 3, 4, 3);
      Moteur_Droite.setRotationPoint(-4F, 19F, 12F);
      Moteur_Droite.setTextureSize(128, 64);
      setRotation(Moteur_Droite, 0F, 0F, 0F);
      Moteur_Gauche = new ModelRenderer(this, 0, 32);
      Moteur_Gauche.addBox(0F, 0F, 0F, 3, 4, 3);
      Moteur_Gauche.setRotationPoint(1F, 19F, 12F);
      Moteur_Gauche.setTextureSize(128, 64);
      setRotation(Moteur_Gauche, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Rembarde_Avant.render(f5);
    Rembarde_Arrière.render(f5);
    Rembarde_Droite.render(f5);
    Rembarde_Gauche.render(f5);
    Moteur_Center.render(f5);
    Moteur_Droite.render(f5);
    Moteur_Gauche.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
