// Date: 10/06/2015 20:41:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package eryah.usefulthings.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Modelplatecrafter extends ModelBase
{
  //fields
    ModelRenderer BasicBloc;
    ModelRenderer Shape2;
    ModelRenderer Shape1;
    ModelRenderer Shape4;
    ModelRenderer Shape3;
  
  public Modelplatecrafter()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BasicBloc = new ModelRenderer(this, 0, 0);
      BasicBloc.addBox(0F, 0F, 0F, 16, 16, 16);
      BasicBloc.setRotationPoint(-8F, 8F, -8F);
      BasicBloc.setTextureSize(64, 64);
      BasicBloc.mirror = true;
      setRotation(BasicBloc, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 34);
      Shape2.addBox(0F, 0F, 0F, 16, 5, 3);
      Shape2.setRotationPoint(-8F, 3F, 5F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 42);
      Shape1.addBox(0F, 0F, 0F, 16, 3, 2);
      Shape1.setRotationPoint(-8F, 0F, 6F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 40, 32);
      Shape4.addBox(0F, 0F, 0F, 4, 3, 6);
      Shape4.setRotationPoint(-2F, 0F, -3F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0.8702893F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 48);
      Shape3.addBox(0F, 0F, 0F, 2, 7, 2);
      Shape3.setRotationPoint(-1F, 0F, 0F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0.8551081F, 0F, 0F);
  }
  
  public void renderAll()
  {
    
    BasicBloc.render(0.0625F);
    Shape2.render(0.0625F);
    Shape1.render(0.0625F);
    Shape4.render(0.0625F);
    Shape3.render(0.0625F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
